#RENDER Database Connection

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7tl143rjlhs73b1kso0-a.ohio-postgres.render.com/veebipood_database_xrod
spring.datasource.username=veebipood_user
spring.datasource.password=Ucv7ocAvcf96KFYqEKRVzfEmtHVLatQP