spring.application.name=veebipood
server.port=8090

spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d75n9k8ule4c73cu3rkg-a.ohio-postgres.render.com/veebipood_database_2uvk
spring.datasource.username=veebipood_user
spring.datasource.password=8bZnRGg9eP40hxHbOJtq34LH2Y9yhG7Y

#veebipood_user
#8bZnRGg9eP40hxHbOJtq34LH2Y9yhG7Y
#postgresql://veebipood_user:8bZnRGg9eP40hxHbOJtq34LH2Y9yhG7Y@dpg-d75n9k8ule4c73cu3rkg-a.ohio-postgres.render.com/veebipood_database_2uvk
